from .view_area import AreaViewSet
from .view_area_nested import AreaEmployeeViewSet, AreaResignViewSet
from .view_department import DepartmentViewSet, SimpleDepartmentViewSet
from .view_department_nested import DepartmentEmployeeViewSet, DepartmentResignViewSet
from .view_employee import EmployeeViewSet, SimpleEmployeeViewSet
from .view_emp import EmployeeCreateViewSet,EmployeeByEmpCodeView
from .view_position import PositionViewSet, SimplePositionViewSet
from .view_position_nested import PositionEmployeeViewSet, PositionResignViewSet
from .view_resign import ResignViewSet
from .view_employeecertification import EmployeeCertificationViewSet
from .view_areagroup import AreaGroupViewSet
